title: "Ingress: Resistance Victoria"
tagline: Enlightenment is a lie. The aliens wish to enslave us. Fight for humanity.

ingress_report_id: LFtMNO8U_88
ingress_beginners_guide: SOAy-_GUQ1Q

profiles:
  development:
    short_name: Dev
    base_url: http://ransom.srw.id.au:4242
  stage:
    short_name: Stage
    base_url: http://stage.resistancevictoria.com
    deploy:
      type: s3
      bucket: s3://stage.resistancevictoria.com/
      uncommitted: true
  production:
    short_name: Home
    base_url: http://resistancevictoria.com
    google_analytics: UA-40180228-1
    minify: true
    deploy:
      type: s3
      bucket: s3://resistancevictoria.com/
