title: Resistance Victoria
tagline: Enlightenment is a lie. The aliens wish to enslave us. Fight for humanity.
short_name: Home
profiles:
  development:
  stage:
    short_name: Stage
    base_url: http://stage.resistancevictoria.com
    deploy:
      type: s3
      bucket: s3://stage.resistancevictoria.com/
  production:
    base_url: http://resistancevictoria.com
    minify: true
    deploy:
      type: s3
      bucket: s3://resistancevictoria.com/
