title: "Ingress: Resistance Victoria"
tagline: Enlightenment is a lie. The aliens wish to enslave us. Fight for humanity.

ingress_report_id: 7VGks1YW67A
ingress_beginners_guide: SOAy-_GUQ1Q

base_url: ''

news:
  text: Resistance Wins Interitus
  url: https://plus.google.com/+Ingress/posts/2Vv7HL1nCqe

profiles:
  development:
    short_name: Dev
  stage:
    short_name: Stage
    deploy:
      type: s3
      bucket: s3://stage.resistancevictoria.com/
      uncommitted: true
  production:
    short_name: Home
    google_analytics:
      account: UA-40180228-2
    minify: true
    haml:
      :ugly: true
    scss:
      :style: :compressed
    deploy:
      type: s3
      bucket: s3://vic.blue/
