title: "Ingress: Resistance Victoria"
tagline: Enlightenment is a lie. The aliens wish to enslave us. Fight for humanity.

ingress_report_id: 8rJhOnQS1Bs
ingress_beginners_guide: SOAy-_GUQ1Q

base_url: ''

profiles:
  development:
    short_name: Dev
  stage:
    short_name: Stage
    deploy:
      type: s3
      bucket: s3://stage.resistancevictoria.com/
      uncommitted: true
  production:
    short_name: Home
    google_analytics:
      account: UA-40180228-1
    minify: true
    deploy:
      type: s3
      bucket: s3://resistancevictoria.com/
