title: "Ingress: Resistance Victoria"
tagline: Enlightenment is a lie. The aliens wish to enslave us. Fight for humanity.

ingress_report_id: RWOuVdG_b68
ingress_beginners_guide: SOAy-_GUQ1Q

base_url: ''

news:
  text: iOS Support Coming Soon! <i class="fa fa-android"></i> <i class="fa fa-heart-o fa-lg"></i> <i class="fa fa-apple"></i>
  url: https://www.youtube.com/watch?v=RWOuVdG_b68

app:
  android: https://play.google.com/store/apps/details?id=com.nianticproject.ingress
  ios: "#soon"

profiles:
  development:
    short_name: Dev
  stage:
    short_name: Stage
    deploy:
      type: s3
      bucket: s3://stage.resistancevictoria.com/
      uncommitted: true
  production:
    short_name: Home
    google_analytics:
      account: UA-40180228-2
    minify: true
    haml:
      :ugly: true
    scss:
      :style: :compressed
    deploy:
      type: s3
      bucket: s3://vic.blue/
