title: "Ingress: Resistance Victoria"
tagline: Enlightenment is a lie. The aliens wish to enslave us. Fight for humanity.

ingress_report_id: T-SZ8FuvJLY
ingress_beginners_guide: SOAy-_GUQ1Q

agent_email: agent@vic.blue

base_url: ''

#news:
#  text: >
#    <strong>Ingress First Saturday #IngressFS</strong> <small>(Saturday 7th Feb, 11:30am)</small><br>
#    Part social, part competitive, Ingress: First Saturday is an Agent-organized free meetup that happens on the first Saturday of the month. Click here for the Melbourne event details <i class="fa fa-arrow-circle-right"></i>
#  url: https://plus.google.com/u/0/events/cgtrj6h16nfjc8u3l9grnt8q9ug

mottoDelay: 5000
mottos:
  -
    - protect
    - humanity
  -
    - <strong>explore</strong>the
    - world
  -
    - fight
    - subjugation
  -
    - <strong>meet</strong>new
    - people
  -
    - enjoy
    - camaraderie
  -
    - level
    - up
  -
    - have
    - fun
  -
    - enjoy
    - teamwork
  -
    - make
    - friends
  -
    - defeat
    - aliens
  -
    - plan
    - events
  -
    - accomplish
    - goals
  -
    - <strong>join</strong>the
    - resistance
  -
    - <strong>free</strong>your
    - mind

app:
  android: https://play.google.com/store/apps/details?id=com.nianticproject.ingress
  ios: https://itunes.apple.com/au/app/ingress/id576505181?mt=8&uo=4

profiles:
  development:
    short_name: Dev
  stage:
    short_name: Stage
    deploy:
      type: s3
      bucket: s3://stage.resistancevictoria.com/
      uncommitted: true
  production:
    short_name: Home
    google_analytics:
      account: UA-40180228-2
    minify: true
    haml:
      :ugly: true
    scss:
      :style: :compressed
    deploy:
      type: s3
      bucket: s3://vic.blue/
